language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: DEPENDENCIES=update
    - php: 7.2
    - php: 7.1
    - php: 7.0.11
    - php: 5.6
      env: 'SCENARIO="phpunit/phpunit:^4.8.36" DEPENDENCIES=update PLATFORM_PHP=5.5.27'
    - php: 5.5
      env: 'SCENARIO="phpunit/phpunit:^4.8.36" DEPENDENCIES=update'
    - php: 5.5
      env: 'SCENARIO="phpunit/phpunit:^4.8.36" DEPENDENCIES="update --prefer-lowest"'

sudo: false

git:
 depth: 10000

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - [ -z "${PLATFORM_PHP}" ] ||  composer -n config platform.php "${PLATFORM_PHP}"
  - [ -z "${SCENARIO}" ] ||  composer -n require --dev --no-update "${SCENARIO}"
  - 'composer "${DEPENDENCIES}"'

before_script:
  - git config --global user.email "travisci@example.com"
  - git config --global user.name "Travis CI Test"

script:
  - composer test
